apiVersion: v1
kind: Namespace
metadata:
  name: splunk-space
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: splunk-forwarder
  namespace: default
  labels:
    k8s-app: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: splunk
  template:
    metadata:
      labels:
        k8s-app: splunk
        name: splunk
    spec:
      hostname: splunk-h-forwarder
      containers:
      - name: splunk
        image: gcr.io/pantel-2decb/splunk:latest
        volumeMounts:
        - name: sa-secret
          mountPath: "/etc/gcp_credentials"
          readOnly: true
        ports:
        - name: web-ui
          containerPort: 8000
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license"
        - name: SPLUNK_USER
          value: "root"
      volumes:
      - name: sa-secret
        secret:
          secretName: splunk-google-application-credentials

