# The Splunk heavy forwarder deployment for GCP
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "splunk-hf-helm.fullname" . }} 
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "splunk-hf-helm.name" . }}
    chart: {{ template "splunk-hf-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "splunk-hf-helm.name" . }}
      chart: {{ template "splunk-hf-helm.chart" . }}
  template:
    metadata:
      labels:
        app: {{ template "splunk-hf-helm.name" . }}
        chart: {{ template "splunk-hf-helm.chart" . }}
    spec:
      hostname: {{ .Values.hostname }}
      containers:
      - name: {{ .Chart.Name }} 
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
        - name: {{ .Values.serviceAccountSecret.name }}
          mountPath: {{ .Values.serviceAccountSecret.mountPath }}
          readOnly: {{ .Values.serviceAccountSecret.readOnly }}
        - name: {{ .Values.splunkCASecret.name }}
          mountPath: {{ .Values.splunkCASecret.mountPath }}
          readOnly: {{ .Values.splunkCASecret.readOnly }}
        - name: {{ .Values.splunkCertsSecret.name }}
          mountPath: {{ .Values.splunkCertsSecret.mountPath }}
          readOnly: {{ .Values.splunkCertsSecret.readOnly }}
        # DEBUG
        ports:
        - name: web-ui
          containerPort: 8000
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license --answer-yes --no-prompt"
      volumes:
      - name: {{ .Values.serviceAccountSecret.name }}
        secret:
          secretName: {{ .Values.serviceAccountSecret.secretName }}
      - name: {{ .Values.splunkCASecret.name }}
        secret: 
          secretName: {{ .Values.splunkCASecret.secretName }}
      - name: {{ .Values.splunkCertsSecret.name }}
        secret: 
          secretName: {{ .Values.splunkCertsSecret.secretName }}

